<form id="doc-form" name="doc-form" method="post" action="<?php echo Mage::getUrl('marketplace/index/save') ?>" enctype="multipart/form-data">
<div id="base_fieldset" class="fieldset ">
    <div class="hor-scroll">
		<table cellspacing="0" class="form-list">
            <tbody>
				<tr>
					<td class="label"><label for="import_file">Select File to Import <span class="required">*</span></label></td>
					<td class="value">
					<input type="file" class=" required-entry" title="Select File to Import" value="" name="docname" id="import_file"></td>
				</tr>
				<tr>
				</tr>
				<tr>
					<td class="label"></td>
					<td class="value">
					<button type="submit" title="Save"><span>Save</span></button>
				</tr>
            </tbody>
        </table>
	</div>
</div>
</form>
