<form name="doc-form" action="<?php echo Mage::getUrl('career/index/radiosave') ?>" method="post" id="career-info">
	<fieldset>
		<ul>
			<li>
				<label for="department" class="required"><em>*</em><?php echo $this->__('Option1') ?></label>
				<div class="input-box">
					<input type="radio" name="1" value="a" checked>Marketing<br>
					<input type="radio" name="1" value="b" >Finance<br>
					<input type="radio" name="1" value="c" >Sales<br>
					<input type="radio" name="1" value="d" >Operation<br>
				</div>
			</li>
			<li>
				<label for="department" class="required"><em>*</em><?php echo $this->__('Option2') ?></label>
				<div class="input-box">
					<input type="radio" name="2" value="a" >Marketing2<br>
					<input type="radio" name="2" value="b" checked>Finance2<br>
					<input type="radio" name="2" value="c" >Sales2<br>
					<input type="radio" name="2" value="d" >Operation2<br>
				</div>
			</li>
			<li>
				<label for="department" class="required"><em>*</em><?php echo $this->__('Option3') ?></label>
				<div class="input-box">
					<input type="radio" name="3" value="a" >Marketing3<br>
					<input type="radio" name="3" value="b" >Finance3<br>
					<input type="radio" name="3" value="c" checked>Sales3<br>
					<input type="radio" name="3" value="d" >Operation3<br>
				</div>
			</li>
			<li>
				<label for="department" class="required"><em>*</em><?php echo $this->__('Option2') ?></label>
				<div class="input-box">
					<input type="radio" name="4" value="a" >Marketing4<br>
					<input type="radio" name="4" value="b" >Finance4<br>
					<input type="radio" name="4" value="c" checked>Sales4<br>
					<input type="radio" name="4" value="d" >Operation4<br>
				</div>
			</li>			
			<li>
				<div class="buttons-set">
					<p class="required"><?php echo $this->__('* Required Fields') ?></p>
					<button type="submit" id="submit" title="<?php echo $this->__('Submit') ?>" class="button"><span><span><?php echo $this->__('Submit') ?></span></span></button>
				</div>
			</li>		
		</ul>
	</fieldset>
</form>
<script type="text/javascript">
//<![CDATA[
	var dataForm = new VarienForm('career-info', true);
//]]>
</script>
    public function RadioAction() {
		$this->loadLayout();   
		$layout = $this->getLayout();
		$this->renderLayout(); 
	}
	public function RadiosaveAction() {
		$itemCount = array();
		$itemCount = array_count_values($this->getRequest()->getParams());
		
		echo '<pre>'; print_r($this->getRequest()->getParams());
		echo '<pre>'; print_r($itemCount);
		echo '<pre>'; print_r(max($itemCount));
		$showProdFor = array_search(max($itemCount), $itemCount);
		echo '<br/>'.$showProdFor;
		if ($showProdFor=='a'){ echo '<br/>option for a======'.$showProdFor; }
		elseif ($showProdFor=='b'){ echo '<br/>option for b ======'.$showProdFor; }
		elseif ($showProdFor=='c'){ echo '<br/>option for c ======'.$showProdFor; }
		else{
			echo '<br/>option for d ======'.$showProdFor;
		}
		die('Done');
		$collection = Mage::getResourceModel('catalog/product_collection');
		$collection->addAttributeToSelect('name','your-attribute');
		$collection->addAttributeToFilter('your-attribute', array('eq' => 'attr-value'));
		/* $ar = array('1','2','4','6','6','2','2','5','2');
			$newArr = array_search(max($ar), $ar);
			echo $newArr; die('xxxxxx');
			echo '<pre>'; print_r(max($newArr)); die('aaaaaaaaaaaa'); 
		*/
	}