<?php  ?>

<div class="account-create">
	<div class="page-title">
		<h1><?php echo $this->__('Create an Account') ?></h1>
	</div>
    <form action="<?php echo Mage::getBaseUrl().'retailer/index/index'; ?>" method="post" >
		<div class="fieldset">
            <h2 class="legend"><?php echo $this->__('ACCOUNT TYPE') ?></h2>
            <ul class="form-list">
                <li class="fields">
                    <div class="field" id="registration">
                        <div class="input-box">
							<input type="radio" name="registration" value="personal"> Personal Account.
							<input type="radio" name="registration" value="retailer"> Wholesale Account.
                        </div>
                    </div>
                </li>
			</ul>
		</div>
		<div class="buttons-set">
            <p class="required"><?php echo $this->__('* Required Fields') ?></p>
            <p class="back-link"><a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>" class="back-link"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
            <button type="submit" title="<?php echo $this->__('Submit') ?>" class="button"><span><span><?php echo $this->__('Submit') ?></span></span></button>
        </div>
    </form>
</div>
<script type="text/javascript">

</script>